from .index import index
from .projects import projects
from .blog import blog
from .blog_post import blog_post
from .add_blog_post import add_blog_post
from .add_project import add_project
from .edit_blog_post import edit_blog_post
from .delete_project import delete_project
from .page404 import page404
