"""empty message

Revision ID: 1c005ba12654
Revises: 58daab6ec5b1
Create Date: 2024-11-15 10:05:09.814413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1c005ba12654'
down_revision: Union[str, None] = '58daab6ec5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogcontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogcontent', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
