"""empty message

Revision ID: ba0f5179ce0c
Revises: f97728669399
Create Date: 2024-11-15 10:12:13.756241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ba0f5179ce0c'
down_revision: Union[str, None] = 'f97728669399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactmessage', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactmessage', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
